#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Seeds the database with initial data needed.
"""
from lib.database import DB
from lib.database.seeds import dat_repos
from lib.database.seeds import dat_rules

with DB as DB:
    dat_repos._import_()
    dat_rules._import_()
